/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software1;

import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class Registro_Cliente extends javax.swing.JFrame {
 Validar validar= new Validar();
 Base base=new Base();
 
 public String CC,Nombre,Apellido,Direccion,Correo, Placa,TelefonoCelular,Cantidad,TipoCliente;
 
 
    public Registro_Cliente() {
        initComponents();
        this.setTitle("Registrar cliente estándar"); 
        this.setLocationRelativeTo(null);
    }

    public void titulo(String titulo){
    
    this.Titulo.setText(titulo);
    
    if(titulo!="Prepago"){
    this.CantidadRC.setVisible(false);
    this.txtCantidadRC.setVisible(false);
    }
    
    }
            
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBotonRegistrar = new javax.swing.JButton();
        PlacaClienteRegistro = new javax.swing.JTextField();
        TelefonoClienteRegistro = new javax.swing.JTextField();
        DireccionClienteRegistro = new javax.swing.JTextField();
        ApellidosClienteRegistro = new javax.swing.JTextField();
        NombreClienteRegistro = new javax.swing.JTextField();
        CCCRegistro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CorreoElectronico = new javax.swing.JTextField();
        jButtonRegresar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        CantidadRC = new javax.swing.JLabel();
        txtCantidadRC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Cedula de Ciudadania");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Dirección");

        jLabel6.setText("Teléfono Celular");

        jLabel7.setText("Placa");

        jBotonRegistrar.setText("Registrar");
        jBotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRegistrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Correo Electronico");

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Titulo.setText("TITULO");

        CantidadRC.setText("Cantidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(CantidadRC)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jBotonRegistrar)))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRegresar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidadRC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorreoElectronico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreClienteRegistro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 45, Short.MAX_VALUE)
                                .addComponent(TelefonoClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PlacaClienteRegistro)
                            .addComponent(DireccionClienteRegistro)
                            .addComponent(ApellidosClienteRegistro)
                            .addComponent(CCCRegistro))
                        .addGap(82, 82, 82))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CCCRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ApellidosClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DireccionClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TelefonoClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlacaClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadRC)
                    .addComponent(txtCantidadRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonRegistrar)
                    .addComponent(jButtonRegresar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRegistrarActionPerformed
        int i=0;
        //{}
       /* if(this.CCCRegistro.getText().equals("") || NombreClienteRegistro.getText().equals("") || this.ApellidosClienteRegistro.getText().equals("") ||
          this.DireccionClienteRegistro.getText().equals("") ||  this.CorreoElectronico.getText().equals("") || this.TelefonoClienteRegistro.equals("") 
                || this.PlacaClienteRegistro.getText().equals("") ){
            JOptionPane.showMessageDialog(null,  "No se permite campos vacios","CAMPOS VACIO", JOptionPane.WARNING_MESSAGE); 
        } */   
           if(this.CCCRegistro.getText().equals(""))
           {
               JOptionPane.showMessageDialog(null,  "Campo obligatorio","CAMPO CC VACIO", JOptionPane.WARNING_MESSAGE); 
           }else if( NombreClienteRegistro.getText().equals("") ){
               JOptionPane.showMessageDialog(null,  "Campo obligatorio","CAMPO NOMBRES VACIO", JOptionPane.WARNING_MESSAGE); 
               }else if(this.ApellidosClienteRegistro.getText().equals(""))
                       {
                           JOptionPane.showMessageDialog(null,  "Campo obligatorio","CAMPO APELLIDOS VACIO", JOptionPane.WARNING_MESSAGE); 
                           } else if (this.DireccionClienteRegistro.getText().equals(""))
                           {
                               JOptionPane.showMessageDialog(null,  "Campo obligatorio","CAMPO DIRECCION VACIO", JOptionPane.WARNING_MESSAGE);  
                           } else if( this.TelefonoClienteRegistro.getText().equals(""))
                               {
                                   JOptionPane.showMessageDialog(null,  "Campo obligatorio","CAMPO TELEFONO CELULAR VACIO", JOptionPane.WARNING_MESSAGE); 
                               }else if(this.PlacaClienteRegistro.getText().equals(""))
                                   {
                                       JOptionPane.showMessageDialog(null,  "Campo obligatorio","CAMPO PLACA DEL VEHICULO VACIO", JOptionPane.WARNING_MESSAGE); 
                                   }else 
            {
              //System.out.println(this.CCCRegistro.getText().toString());
              if (validar.validarCC(this.CCCRegistro.getText().toString()))
                  {
                      //{}
                      i++;
                      this.CC=this.CCCRegistro.getText().toString();
                      //System.out.println("cc: "+this.CCCRegistro.getText().toString() );
                  }
              if(validar.validarTex(this.NombreClienteRegistro.getText().toString()))
               {
                   i++;
               this.Nombre= this.NombreClienteRegistro.getText().toString();
               //System.out.println(this.NombreClienteRegistro.getText().toString());
               
               }
              
              if(validar.validarTex(this.ApellidosClienteRegistro.getText().toString()))
               {
                   i++;
                   this.Apellido=this.ApellidosClienteRegistro.getText().toString();
                   //System.out.println(this.ApellidosClienteRegistro.getText().toString());
               }
              
              if(validar.validarDireccion(this.DireccionClienteRegistro.getText().toString()))
              {
                  i++;
                this.Direccion=this.DireccionClienteRegistro.getText().toString();
               // System.out.println("aqui "+this.DireccionClienteRegistro.getText().toString());      
              }
              if(validar.validarCorreo(this.CorreoElectronico.getText().toString()))
              {i++;
                  this.Correo=this.CorreoElectronico.getText().toString();
                  //System.out.println(this.CorreoElectronico.getText().toString());
              }
              if(validar.validarTelefonoC(this.TelefonoClienteRegistro.getText()))
              {i++;
                  this.TelefonoCelular=this.TelefonoClienteRegistro.getText();
                 // System.out.println(this.TelefonoClienteRegistro.getText());
              }
              if(validar.validarPlaca(this.PlacaClienteRegistro.getText().toString()))
              {i++;
                  this.Placa=this.PlacaClienteRegistro.getText().toString();
                 // System.out.println(this.PlacaClienteRegistro.getText().toString());
              }
              
              
              
              
              if(i==7)
               {
                JOptionPane.showMessageDialog(null,  "CLIENTE REGISTRADO"); 
                this.TipoCliente=this.Titulo.getText().toString();
                this.base.crearArchivo(this.CC,this.TipoCliente,this.Nombre,this.Apellido,this.Direccion,this.Correo,this.TelefonoCelular,this.Placa);
               }
            }  
        
        
        
    }//GEN-LAST:event_jBotonRegistrarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
                this.setVisible(false);
                  Menu m=new Menu();
               m.setVisible(true);
               m.setEnabled(true);
        
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosClienteRegistro;
    private javax.swing.JTextField CCCRegistro;
    private javax.swing.JLabel CantidadRC;
    private javax.swing.JTextField CorreoElectronico;
    private javax.swing.JTextField DireccionClienteRegistro;
    private javax.swing.JTextField NombreClienteRegistro;
    private javax.swing.JTextField PlacaClienteRegistro;
    private javax.swing.JTextField TelefonoClienteRegistro;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jBotonRegistrar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidadRC;
    // End of variables declaration//GEN-END:variables
}
